### PR TITLE
Release version 2.1.1

### PR DESCRIPTION
**Pull request by dobey**

### CODE REVIEW

**Review by bhush9 — APPROVED** [review]

**Comment by KAMiKAZOW** [comment]
Can we remove the CMake rules that install readme files first, as @PureTryOut suggested?

**Comment by dobey** [comment]
> Can we remove the CMake rules that install readme files first, as @PureTryOut suggested?

I think we don't need to rush that in. I'd like to know why it was done in the first place, before removing it for example. Maybe @jpetersen or @mikhas can answer.

I've tagged the released so that we can have the fixed install tarball out.

**Comment by jpetersen** [comment]
> > Can we remove the CMake rules that install readme files first, as @PureTryOut suggested?
> 
> I think we don't need to rush that in. I'd like to know why it was done in the first place, before removing it for example. Maybe @jpetersen or @mikhas can answer.

I do not remember if ther was any speciifc reason maybe other software used to do that as well. In between we also had packaging rules for debian directly included in the repository for Maemo so if one normally does not install readmes we do not need to do it either.

**Comment by KAMiKAZOW** [comment]
FYI: I've noticed that the release was not showing up on the main page (only if you clicked on the Releases page and then it was collapsed). I've written a one-liner of a release announcement and now it's showing up. I did not tag a new release but it's showing a release date of a few minutes ago now. That should be cosmetic only.

**Pull request merged**
